# Generated by Django 4.2.11 on 2024-06-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("Data", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=250)),
            ],
        ),
    ]
