# Generated by Django 4.2.11 on 2024-06-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Project1", new_name="Blog",),
    ]
