# Generated by Django 4.2.11 on 2024-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_project1_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="Data", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=200),
        ),
    ]
